pipeline {
    agent any

    stages {

        stage('Install & Build') {
            agent {
                docker {
                    image 'node:18-alpine'
                    reuseNode true
                }
            }

            steps {
                sh '''
                    node --version
                    npm --version

                    npm ci
                    npm run build
                '''
            }
        }

        stage('Test') {
            agent {
                docker {
                    image 'node:18-alpine'
                    reuseNode true
                }
            }

            steps {
                sh '''
                    npm test
                '''
            }
        }

        stage('E2E') {
            agent {
                docker {
                    image 'mcr.microsoft.com/playwright:v1.39.0-jammy'
                    reuseNode true
                }
            }

            steps {
                sh '''
                    # Fix npm cache permission issue in Playwright image
                    export NPM_CONFIG_CACHE=/tmp/.npm

                    # Install serve safely
                    npm install -g serve

                    # Serve production build
                    serve -s build -l 3000 &
                    sleep 10

                    # Run Playwright tests
                    npx playwright test --reporter=html
                '''
            }
        }
    }

    post {
        always {
            // JUnit report (if generated by Jest)
            junit allowEmptyResults: true, testResults: 'jest-results/junit.xml'

            // Playwright HTML report
            publishHTML([
                allowMissing: true,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'playwright-report',
                reportFiles: 'index.html',
                reportName: 'Playwright HTML Report'
            ])
        }
    }
}
